### ISSUE TITLE
Monthly income option

### ISSUE THREAD

**Issue by teobais** [stevermeister/dutch-tax-income-calculator-old#31]
Hey, nice project!

There are differences among companies: some of them provide a 13th salary, whereas others, a 14th.
For this purpose, except from having to specifically update the holiday allowance (assumption without investigating the code itself) option, it should be also good to provide an option for the end-user to enter his monthly income, instead of restricting him to his annual.

**Comment by stevermeister** [comment]
@toubou91 ,
thank you for your feedback.
it would be really nice addition and I'll try to include option so set monthly income next release

**Comment by toubou91** [comment]
@stevermeister cool, I can also help with this, if we come to an agreement, regarding which fields to hide/show/include for this purpose and also how to provide both options (monthly/annual income) in a visible way to the user.

**Comment by teobais** [comment]
@stevermeister cool, I can also help with this. What I foresee (and please correct me, if I'm getting any of the logistics out of consideration) as a solution for having both options enabled and not a pain for the end-user, is, providing a solution, where:
- Radiobuttons (red signs in the picture below)/ckeckbox (in the same position with the current label for annual income) could be used to toggle the income's state (monthly/annual)
- Income components will be updated/hidden/displayed respectively (blue crosses in the picture below are used for the use case of monthly income request; I guess this is the only affected field from a brief look at the listed ones)

![image](https://cloud.githubusercontent.com/assets/5684688/16056719/1e26beca-3277-11e6-9223-1492c04a8351.png)

If you have another implementation in mind, regarding which fields to hide/show/include for this purpose and how to also provide both options (monthly/annual income) in a visible way to the user, please let me know.

**Comment by stevermeister** [comment]
@toubou91,
I've started branch for it. The logic is pretty tricky and you are welcome to contribute ;)

**Comment by Cy-napse** [comment]
Hello stevermeister

Really like your Dutch income tax calculator, so easy and useful! Thanks for this.

I have one question about it, I've been scratching my head trying to understand this: why does the "holiday allowance included" _lower_ the taxable income and the net income? 

I may be thinking about this wrong or misunderstanding this (as I'm new to the Dutch tax system, I am considering moving to the Netherlands), but I can't make sense of it. I understand the holiday allowance to be also taxable income.

To take an example:
If my employer tells me that my annual gross income is 100k
and that the holiday allowance is included in that gross income
it is taxable at the marginal rate
so I would expect the taxable income to be 100k
(and then the income tax to be 45,150 -- if under 65 years old and no 30% tax ruling)

But instead if I click the "holiday allowance included" button, it lowers the taxable income to 92,593! Why?

If the holiday allowance is not included and applies
then does it not get added to the 100k
so that the total taxable income is 108k?

Sorry if I am getting this wrong and am confused... please help me understand.

Thanks in advance for educating me on this!

**Comment by stevermeister** [comment]
@toubou91 
this functionality will be included in V3, already working on it. 
you can check - https://github.com/stevermeister/dutch-tax-income-calculator2 (based on Angular2)

**Comment by jimaldon** [comment]
@stevermeister Does the monthly income in the present version (when the Holiday Allowance Included radio button is enabled) tell the nett income each month for 12 months? Or 13 months?

Like have you divided the 13th month income by 12 and added it to each for the 12 months to display the monthly netto income?

**Comment by stevermeister** [comment]
12
