### ISSUE TITLE
Add this.ruling.choice = 'young' to be able to calculate 30% ruling for master graduates under 30.

### ISSUE THREAD

**Issue by andelizondo** [stevermeister/dutch-tax-income-calculator-old#61]
Please add an extra checkbox that changes `this.ruling.choice` from 'normal' (this is default) to 'young'

**Comment by stevermeister** [comment]
could you provide more details, please?

**Comment by PWDrew** [comment]
As described at the bottom of your page, If you're below the age of 30 and have a masters your 30% ruling kicks in at 28000, not 37000. But the default in your application is 37000, and cannot be changed.

**Comment by stevermeister** [comment]
thank you for the feedback! 
I got the point, made a hotfix for it: to allow ruling for young age by default

**Comment by endertunc** [comment]
Hi @stevermeister,  I think we need to fix the issue ASAP because http://thetax.nl is one of the most popular tools there available and people might count on it. With the latest update, the current system might show more than what people really get (like in my case under age 30 without a master degree).

I was thinking of making a PR and looks like (almost) everything there but not just activated for some reason. I will try to make it work but just want to know if there is something I am missing.

Thanks.

**Comment by andelizondo** [comment]
I agree with @endertunc, my idea when I created the issue was to include an additional checkbox for people less than 30 and with a masters... but now this options goes by default, which is not correct behavior...

**Comment by stevermeister** [comment]
Unfortunately, I don't have time for it right now. I made just a hotfix to let it work if you are younger than 30.
@endertunc @andelizondo you are more than welcome to create PR for it.
