### ISSUE TITLE
Holiday allowance included is greyed out

### ISSUE THREAD

**Issue by npiracha** [stevermeister/dutch-tax-income-calculator-old#70]
I am unable to select the option to include holiday allowance. Is this a temporary issue? Thanks

**Comment by stevermeister** [comment]
it appeared to be a pretty confusing option: when it's on - does it mean that it's already in gross salary or should it be added on top? 

for now, I just disable it till somebody suggest clear UX solution for it

**Comment by asyschikov** [comment]
The holiday allowance option is very useful and important, so it would be great if you can enable it. To the point that I just go to Inspect Element and remove the `disabled `attribute and it works perfectly! The simplest solution would be to extend the label to "Holliday allowance is included in the annual gross income". I think it will make it more clear. A better and more complex approach would be to have a selection of something like 3 options: 

- No holiday allowance
- Holiday allowance included in the annual gross
- Add holiday allowance to the annual gross

And the third option will add 8% on top of what user entered.

**Comment by stevermeister** [comment]
>  Inspect Element and remove the disabledattribute and it works perfectly! 

I love to do applications for developers :)

> And the third option will add 8% on top of what user entered.
It could be also tricky, because sometimes allowance is not 8%, right? 



But what is exactly your issue? 
could you please explain me the use case?
do you have gross year salary and holiday allowance is already there(in this amount)?

**Comment by asyschikov** [comment]
@stevermeister The issue is that sometimes you are told the salary with the allowance included sometimes without. If I understand it correctly the difference in the tax calculation and monthly income is this:

- If it is included in the annual total then your monthly net income is `((annual - taxes) - 8%) / 12`.
- If you have the annual total without the holiday allowance then your monthly net income is `(((annual + 8%) - taxes) - 8%) / 12`.

The factor here is that the taxable annual income always includes the allowance.

**Comment by NilsAr** [comment]
I agree, would really like to get the "holiday allowance included" feature back. Many employers (in particular startups) give people the "gross salary _including holiday allowance_" to make the gross salary look larger. My employer does this too and is very annoying.

With the option greyed out, it becomes very difficult to estimate what net income one would get in case of a salary raise including holiday allowance.

@asyschikov Where do I find the `disabled` attribute? (non-coding knowledge here...)

**Comment by tangvip** [comment]
I also agree that the holiday allowance(HA) should return. 
The problem is not the annual net income estimation but the monthly income estimation. 
If the HA is included, then the **MonthNetIncome = AnnualNetIncome/1.08/12**

Another aspect is some company also provide 13th-month salary, which is approximatly also equals to 8% of annually gross salary(MonthlyGross\*12\*0.08). If that is the case, the  MonthNetIncome  should be further adjusted.

**Comment by evrenesat** [comment]
My company also account holiday allowance in the yearly gross so, with its current form, the calculator doesn't show monthly net salary correctly. The only benefit of the current design is, it signs to the user that what his/her employer is doing is not common or right :) Is this a correct assumption?

**Comment by stevermeister** [comment]
ok, I return back holiday allowance check.
