### ISSUE TITLE
'Ruling Real Percentage' not working

### ISSUE THREAD

**Issue by tiagofilipe1** [stevermeister/dutch-tax-income-calculator-old#92]
Hi, I believe you have disabled the option of the partial 30% rule when you commented out the following code:

   if (salary.taxableYear < rulingIncome) { // For partial 
     salary.taxFreeYear = grossYear - rulingIncome; 
     salary.taxableYear = rulingIncome; 
   } 

Without this condition, the 30% rule is always either 0 or 30.
However, that is not the real case. It can take any value between 0 and 30, depending on the gross yearly salary.
Could you add that condition back to the code please?

**Comment by stevermeister** [comment]
answered in https://github.com/stevermeister/dutch-tax-income-calculator/issues/85

**Comment by aSemy** [comment]
I believe this code will work to correctly calculate the 30% ruling, but I'm not 100% sure how the ruling works, and it's also difficult for me to tell how this will interact with other options selected.

The basic process comes from [this website](https://www.expatica.com/nl/finance/taxes/the-dutch-30-ruling-explained-101641/ ), and my own notes.

1. Take 70% of the taxable salary. I've named this `effectiveSalary`.
2. If this is *under* the `rulingIncome` then `effectiveSalary` is capped at the `rulingIncome`. Else, continue.
3. Calculate the taxFree amount: taxable salary minus `effectiveSalary` 

I'm not fluent with Javascript, so please check this carefully.

I'd really appreciate it @stevermeister if you could select a test framework and implement even a single basic test so that we could add some more tests :). I wouldn't want to make a PR without tests.

```javascript
        if (this.ruling.checked) {
         let rulingIncome = getRulingIncome(this.year, this.ruling.choice);
         // the 30% of taxableYear is untaxed
         // UNLESS this brings taxableYear under the rulingIncome
         // in which case cap the effectiveSalary to rulingIncome
         let effectiveSalary = salary.taxableYear * 0.7;
         effectiveSalary = Math.max(effectiveSalary, rulingIncome);
         let reimbursement = salary.taxableYear - effectiveSalary;
         if (reimbursement > 0) {
           salary.taxFreeYear = reimbursement;
           salary.taxableYear = salary.taxableYear - reimbursement;
         }
       }
```

EDIT: Don't use `grossYear` as the base - use `taxableYear`

**Comment by stevermeister** [comment]
@aSemy thank you for your contribution.
yes, true, we definitely need to have tests.
I plan to rewrite the code a bit to have logic separately and then cover with tests.

so I've applied your changes, please check. 

@tiagofilipe1 please also have a look

**Comment by aSemy** [comment]
Great, thanks @stevermeister! It looks good to me, and like the issues raised in #85 are resolved.

**Comment by stevermeister** [comment]
glad to hear. 
and I really hope that I'll find some time for tests in the future :)
